---
- name: server details
  hosts: dannt
  remote_user: ubuntu
  become: true

  tasks:
  - name: install wget
    apt:
      name: wget
      state: present
  - name: install telnet
    apt: 
      name: telnet
      state: present
  - name: Creates directory
    file:
      path: /home/abc
      state: directory

    
