---
- name: server details
  hosts: dannt
  remote_user: ubuntu
  become: true

  tasks:
  - name: install wget
    apt:
      name: wget
      state: present
  - name: install httpd
    apt: 
      name: {{item}}
      state: present
    with_items: 
    - httpd
    