---
- name: server details
  hosts: dannt
  remote_user: ubuntu
  become: true

  tasks:
  - name: install wget
    apt:
      name: wget
      state: present
  - name: install git
    apt:
      name: git
      state: present
  - name: Creates directory
    file:
      path: /home/repo
      state: directory
  - name: clone code
    command:
      chdir: /home/repo
      cmd: sudo rm -rf awx
      cmd: git clone https://github.com/dannt94/awx.git
  - name: deploy application with ansible
    command:
      chdir: /home/repo/awx 
      cmd: ansible-playbook playbook.yml